name: Node.js package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.4
          run_install: |
            args: [--frozen-lockfile]
      - name: Setup Node.js environment for GitHub Package Registry
        uses: actions/setup-node@v2
        with:
          scope: ${{github.repository_owner}}
          registry-url: https://npm.pkg.github.com/
      - name: Publish package to GitHub Package Registry
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB}}
      - name: Setup Node.js environment for npm
        uses: actions/setup-node@v2
        with:
          scope: ${{github.repository_owner}}
          registry-url: https://registry.npmjs.org/
      - name: Publish package to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
